WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-24 18:26:26,797 WARNING 19161 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-24 18:26:26,798 WARNING 19161 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-24 18:26:31,111 WARNING 19161 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-24 18:26:34,330 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 18:26:39,353 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 18:26:46,376 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 18:26:55,394 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 18:27:06,417 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 18:27:19,455 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 18:27:34,482 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 18:27:51,527 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 18:28:10,557 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 18:28:31,592 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 18:28:54,625 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 18:29:19,668 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 18:29:46,889 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 18:30:15,929 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 18:30:47,416 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 18:31:20,458 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:31:55,886 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:32:30,930 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:33:06,619 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:33:41,664 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:34:16,910 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:34:51,957 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:35:27,202 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:36:02,358 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:36:37,422 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:37:12,519 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:37:47,575 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:38:22,631 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:38:57,699 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:39:32,764 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:40:07,812 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:40:42,858 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:41:17,908 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:41:52,967 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:42:28,012 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:43:03,050 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:43:38,094 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:44:13,141 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:44:48,190 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:45:23,251 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:45:58,306 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:46:33,411 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:47:08,476 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:47:43,527 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:48:18,574 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:48:53,615 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:49:28,655 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:50:03,951 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:50:39,498 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:51:14,552 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:51:49,600 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:52:24,643 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:52:59,709 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:53:34,763 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:54:09,806 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:54:44,866 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:55:19,935 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:55:55,023 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:56:30,084 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:57:05,665 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:57:40,853 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:58:15,992 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:58:51,034 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 18:59:26,091 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:00:01,138 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:00:36,198 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:01:11,249 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:01:46,306 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:02:21,370 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:02:56,442 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:03:31,488 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:04:06,549 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:04:41,597 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:05:16,645 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:05:51,688 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:06:26,740 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:07:01,782 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:07:36,833 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:08:11,912 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:08:46,969 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:09:22,021 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:09:57,175 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:10:32,239 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:11:07,320 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:11:42,385 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:12:17,437 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:12:52,483 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:13:27,533 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:14:02,580 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:14:38,021 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:15:13,070 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:15:48,143 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:16:23,213 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:16:58,277 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:17:33,330 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:18:08,392 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:18:43,462 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:19:18,547 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:19:53,650 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:20:28,795 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:21:07,007 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 19:21:12,038 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 19:21:19,058 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 19:21:28,083 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 19:21:39,123 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 19:21:52,156 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 19:22:07,234 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 19:22:24,276 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 19:22:43,320 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 19:23:04,386 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 19:23:27,445 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 19:23:52,509 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 19:24:19,592 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 19:24:48,661 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 19:25:19,710 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 19:25:52,798 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:26:27,877 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:27:02,955 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:27:38,043 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:28:13,150 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:28:48,262 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:29:23,372 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:29:58,442 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:30:33,756 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:31:08,830 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:31:43,911 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:32:18,991 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:32:54,067 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:33:29,141 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:34:04,257 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:34:39,349 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:35:14,415 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:35:49,517 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:36:24,637 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:36:59,719 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:37:34,793 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:38:09,853 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:38:44,934 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:39:20,032 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:39:55,110 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:40:30,184 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:41:05,275 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:41:40,350 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:42:15,512 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:42:50,648 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:43:26,350 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:44:01,450 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:44:36,547 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:45:11,844 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:45:46,941 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:46:22,011 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:46:57,096 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:47:32,309 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:48:07,386 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:48:42,468 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:49:17,547 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:49:52,618 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:50:27,719 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:51:02,820 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:51:37,910 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:52:13,017 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:52:48,101 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:53:23,177 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:53:58,246 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:54:33,324 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:55:08,644 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:55:44,024 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:56:19,098 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:56:54,157 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:57:29,261 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:58:04,372 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:58:39,423 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:59:14,482 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 19:59:49,538 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:00:24,600 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:00:59,658 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:01:34,726 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:02:09,792 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:02:44,859 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:03:20,368 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:03:55,431 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:04:31,114 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:05:06,290 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:05:41,382 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:06:16,461 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:06:51,529 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:07:26,595 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:08:01,673 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:08:36,742 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:09:11,815 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:09:46,886 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:10:21,957 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:10:57,023 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:11:32,091 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:12:07,168 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:12:42,248 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:13:17,307 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:13:52,404 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:14:27,470 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:15:02,539 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:15:40,671 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 20:15:45,711 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 20:15:52,740 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 20:16:01,775 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 20:16:12,809 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 20:16:25,875 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 20:16:40,942 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 20:16:57,981 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 20:17:17,026 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 20:17:38,081 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 20:18:01,133 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 20:18:26,421 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 20:18:53,504 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 20:19:22,609 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 20:19:53,689 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 20:20:26,761 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:21:01,885 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:21:36,991 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:22:12,386 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:22:47,470 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:23:22,537 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:23:57,633 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:24:32,728 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:25:07,803 ERROR 19161 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-24 20:30:10,385 WARNING 24921 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-24 20:30:10,387 WARNING 24921 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-24 20:30:27,576 WARNING 24921 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-24 20:30:31,839 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 20:30:36,876 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 20:30:43,928 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 20:30:53,442 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 20:31:04,489 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 20:31:17,526 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 20:31:32,594 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 20:31:49,655 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 20:32:08,759 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 20:32:29,835 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 20:32:52,904 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 20:33:18,285 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 20:33:45,381 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 20:34:14,464 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 20:34:45,582 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 20:35:18,674 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:35:54,171 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:36:29,248 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:37:04,319 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:37:39,686 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:38:15,397 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:38:50,503 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:39:26,118 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:40:01,184 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:40:36,247 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:41:11,306 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:41:46,387 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:42:21,463 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:42:56,537 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:43:31,621 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:44:06,686 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:44:42,139 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:45:17,420 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:45:52,494 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:46:27,550 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:47:02,626 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:47:37,690 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:48:12,766 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:48:47,836 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:49:22,903 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:49:57,987 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:50:33,076 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:51:08,158 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:51:43,243 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:52:18,307 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:52:53,386 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:53:28,456 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:54:03,527 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:54:38,824 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:55:13,908 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:55:48,987 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:56:24,049 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:56:59,123 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:57:34,202 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:58:09,407 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:58:44,491 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:59:19,587 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 20:59:54,665 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:00:29,727 ERROR 24921 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-24 21:02:56,122 WARNING 13579 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-24 21:02:56,123 WARNING 13579 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-24 21:03:32,819 WARNING 13579 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-24 21:03:36,512 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 21:03:41,544 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 21:03:48,573 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 21:03:57,606 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 21:04:08,638 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 21:04:21,678 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 21:04:36,719 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 21:04:53,791 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 21:05:12,823 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 21:05:33,886 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 21:05:56,982 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 21:06:22,184 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 21:06:49,251 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 21:07:18,309 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 21:07:49,390 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 21:08:22,471 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:08:57,588 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:09:32,693 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:10:07,784 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:10:42,938 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:11:18,034 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:11:53,191 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:12:28,271 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:13:03,364 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:13:38,438 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:14:13,555 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:14:48,682 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:15:24,177 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:15:59,303 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:16:34,427 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:17:09,483 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:17:44,572 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:18:19,908 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:18:54,978 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:19:30,138 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:20:05,214 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:20:40,283 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:21:15,405 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:21:50,610 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:22:25,693 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:23:00,796 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:23:35,881 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:24:11,072 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:24:46,345 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:25:21,447 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:25:56,535 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:26:31,627 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:27:06,734 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:27:41,805 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:28:16,914 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:28:52,022 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:29:27,112 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:30:02,216 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:30:37,300 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:31:12,372 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:31:47,466 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:32:22,585 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:32:57,685 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:33:32,867 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:34:08,042 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:34:43,120 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:35:18,212 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:35:53,276 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:36:28,336 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:37:03,416 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:37:38,511 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:38:13,588 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:38:48,674 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:39:24,100 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:39:59,478 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:40:34,556 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:41:09,649 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:41:44,766 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:42:19,832 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:42:54,902 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:43:30,453 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:44:05,525 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:44:40,589 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:45:15,656 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:45:50,721 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:46:25,801 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:47:00,882 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:47:35,950 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:48:11,011 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:48:46,072 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:49:21,145 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:49:56,210 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:50:31,275 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:51:06,336 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:51:41,430 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:52:16,502 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:52:51,569 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:53:26,643 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:54:01,721 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:54:36,803 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:55:11,923 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:55:47,000 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:56:22,083 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:56:57,159 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:57:32,318 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 21:58:10,950 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 21:58:16,157 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 21:58:23,314 ERROR 13579 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-24 22:01:31,586 WARNING 15992 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-24 22:01:31,589 WARNING 15992 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-24 22:01:44,891 WARNING 15992 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-24 22:01:48,988 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 22:01:54,031 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 22:02:01,057 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 22:02:10,100 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 22:02:21,138 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 22:02:34,197 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 22:02:49,244 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 22:03:06,465 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 22:03:25,526 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 22:03:46,596 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 22:04:10,062 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 22:04:35,160 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 22:05:02,290 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 22:05:31,396 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 22:06:02,501 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 22:06:35,592 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:07:10,670 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:07:45,781 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:08:20,879 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:08:55,982 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:09:31,083 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:10:06,162 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:10:41,222 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:11:16,298 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:11:51,370 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:12:26,453 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:13:01,516 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:13:36,622 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:14:11,711 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:14:46,789 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:15:22,335 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:15:57,407 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:16:32,471 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:17:07,567 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:17:42,655 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:18:17,740 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:18:52,807 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:19:27,881 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:20:02,958 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:20:38,055 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:21:13,139 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:21:48,209 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:22:23,283 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:22:58,449 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:23:33,562 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:24:08,719 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:24:43,882 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:25:18,976 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:25:54,051 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:26:29,529 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:27:04,666 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:27:39,752 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:28:15,226 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:28:51,056 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:29:26,144 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:30:01,220 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:30:36,307 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:31:11,381 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:31:46,482 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:32:21,573 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:32:56,660 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:33:31,726 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:34:06,828 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:34:41,920 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:35:17,003 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:35:52,142 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:36:27,392 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:37:02,486 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:37:37,564 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:38:12,627 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:38:47,721 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:39:22,813 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:39:57,886 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:40:33,018 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:41:08,114 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:41:43,203 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:42:18,313 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:42:53,399 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:43:28,539 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:44:03,630 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:44:38,702 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:45:13,776 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:45:48,851 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:46:23,918 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:46:58,982 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:47:34,057 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:48:09,149 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:48:44,293 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:49:19,373 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:49:54,529 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:50:29,607 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:51:04,676 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:51:40,061 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:52:15,148 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:52:50,268 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:53:25,381 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:54:00,442 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:54:35,742 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:55:10,806 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:55:45,869 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 22:56:23,943 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 22:56:28,965 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 22:56:35,988 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 22:56:45,012 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 22:56:56,044 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 22:57:09,078 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 22:57:24,119 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 22:57:41,155 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 22:58:00,193 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 22:58:21,226 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 22:58:44,279 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 22:59:09,803 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 22:59:36,852 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 23:00:05,900 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 23:00:36,949 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 23:01:10,004 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:01:45,054 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:02:20,142 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:02:55,210 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:03:30,298 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:04:05,747 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:04:40,816 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:05:15,887 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:05:50,940 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:06:26,000 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:07:01,062 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:07:36,132 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:08:11,206 ERROR 15992 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-24 23:10:56,152 WARNING 21056 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-24 23:10:56,152 WARNING 21056 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-24 23:11:29,372 WARNING 21056 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-24 23:11:33,004 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-24 23:11:38,052 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-24 23:11:45,076 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-24 23:11:54,097 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-24 23:12:05,237 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-24 23:12:18,294 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-24 23:12:33,333 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-24 23:12:50,414 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-24 23:13:09,509 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-24 23:13:30,576 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-24 23:13:53,634 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-24 23:14:18,704 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-24 23:14:45,814 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-24 23:15:14,879 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-24 23:15:45,937 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-24 23:16:19,009 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:16:54,409 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:17:29,503 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:18:04,593 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:18:39,666 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:19:14,735 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:19:50,194 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:20:25,292 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:21:00,362 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:21:35,569 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:22:10,639 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:22:45,701 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:23:20,785 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:23:56,599 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:24:32,439 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:25:07,482 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:25:42,583 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:26:18,076 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:26:53,354 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:27:28,419 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:28:03,488 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:28:38,564 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:29:13,623 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:29:48,694 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:30:23,777 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:30:58,865 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:31:33,947 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:32:09,191 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:32:44,258 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:33:19,341 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:33:54,423 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:34:29,506 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:35:04,604 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:35:39,491 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:36:14,578 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:36:49,667 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:37:24,755 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:37:59,917 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:38:34,989 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:39:10,076 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:39:45,187 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:40:20,285 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:40:55,372 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:41:30,464 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:42:05,598 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:42:40,676 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:43:15,784 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:43:50,896 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:44:25,984 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:45:01,049 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:45:36,120 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:46:11,189 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:46:46,552 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:47:21,616 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:47:56,874 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:48:31,967 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:49:07,050 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:49:42,165 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:50:17,251 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:50:52,345 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:51:27,410 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:52:02,501 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:52:37,639 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:53:12,728 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:53:47,803 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:54:22,871 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:54:57,943 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:55:33,303 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:56:08,402 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:56:43,487 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:57:18,546 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:57:53,606 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:58:28,691 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:59:03,786 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-24 23:59:38,851 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:00:13,942 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:00:49,012 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:01:24,103 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:01:59,168 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:02:34,253 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:03:09,342 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:03:44,418 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:04:19,493 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:04:54,575 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:05:29,643 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:06:07,859 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-25 00:06:12,878 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-25 00:06:19,769 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-25 00:06:28,831 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-25 00:06:39,938 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-25 00:06:52,995 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-25 00:07:08,044 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-25 00:07:25,122 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-25 00:07:44,415 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-25 00:08:05,480 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-25 00:08:28,583 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-25 00:08:53,676 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-25 00:09:20,770 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-25 00:09:49,861 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-25 00:10:20,956 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-25 00:10:54,058 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:11:29,137 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:12:04,286 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:12:39,386 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:13:14,468 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:13:49,533 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:14:24,584 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:14:59,638 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:15:34,696 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:16:09,765 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:16:44,824 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:17:19,884 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:17:54,936 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:18:30,086 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:19:05,638 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:19:40,752 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:20:16,053 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:20:51,232 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:21:26,365 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:22:01,520 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:22:36,611 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:23:12,118 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:23:47,187 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:24:22,248 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:24:57,334 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:25:32,485 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:26:07,856 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:26:43,110 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:27:18,167 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:27:53,236 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:28:28,316 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:29:03,392 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:29:38,461 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:30:13,557 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:30:48,623 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:31:23,723 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:31:58,806 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:32:33,891 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:33:08,967 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:33:44,061 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:34:19,172 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:34:54,274 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:35:29,340 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:36:04,397 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:36:39,463 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:37:14,528 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:37:49,585 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:38:24,650 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:38:59,737 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:39:34,791 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:40:09,857 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:40:44,916 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:41:19,979 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:41:55,038 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:42:30,274 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:43:05,338 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:43:40,396 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:44:15,455 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:44:50,521 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:45:25,614 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:46:00,687 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:46:35,754 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:47:10,816 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:47:45,879 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:48:20,935 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:48:55,996 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:49:31,051 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:50:06,125 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:50:41,209 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:51:16,307 ERROR 21056 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-25 00:53:37,562 WARNING 15140 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-25 00:53:37,563 WARNING 15140 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-25 00:53:53,889 WARNING 15140 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-25 00:53:57,498 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-25 00:54:02,998 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-25 00:54:10,220 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-25 00:54:19,242 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-25 00:54:30,276 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-25 00:54:43,318 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-25 00:54:58,371 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-25 00:55:15,407 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-25 00:55:34,462 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-25 00:55:55,568 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-25 00:56:18,634 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-25 00:56:43,726 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-25 00:57:10,777 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-25 00:57:39,846 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-25 00:58:10,916 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-25 00:58:43,972 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:59:19,029 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 00:59:54,118 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:00:29,235 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:01:04,288 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:01:39,788 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:02:14,853 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:02:49,994 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:03:25,057 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:04:00,131 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:04:35,218 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:05:10,279 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:05:45,334 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:06:20,388 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:06:55,455 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:07:30,507 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:08:05,577 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:08:40,643 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:09:15,714 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:09:50,781 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:10:25,869 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:11:00,946 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:11:36,022 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:12:11,085 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:12:46,151 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:13:21,230 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:13:56,301 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:14:31,363 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:15:06,441 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:15:41,514 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:16:16,590 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:16:51,663 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:17:26,724 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:18:01,786 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:18:36,860 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:19:11,987 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:19:47,119 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:20:22,219 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:20:57,287 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:21:32,408 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:22:07,998 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:22:43,113 ERROR 15140 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...


worker: Warm shutdown (MainProcess)
WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-03-25 01:25:36,771 WARNING 4662 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-03-25 01:25:36,790 WARNING 4662 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-03-25 01:26:12,277 WARNING 4662 [py.warnings] worker.py:161 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2020-03-25 01:26:15,791 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

2020-03-25 01:26:20,808 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

2020-03-25 01:26:27,836 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

2020-03-25 01:26:36,882 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

2020-03-25 01:26:47,917 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

2020-03-25 01:27:00,959 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

2020-03-25 01:27:16,215 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

2020-03-25 01:27:33,250 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

2020-03-25 01:27:52,298 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

2020-03-25 01:28:14,199 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

2020-03-25 01:28:37,281 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

2020-03-25 01:29:02,361 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

2020-03-25 01:29:29,439 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

2020-03-25 01:29:58,565 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

2020-03-25 01:30:29,662 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

2020-03-25 01:31:02,760 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:31:37,853 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:32:12,954 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:32:48,028 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:33:23,110 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:33:58,186 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:34:33,253 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:35:08,357 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:35:43,429 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:36:18,500 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:36:53,568 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:37:28,946 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:38:04,029 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:38:39,151 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:39:14,249 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:39:49,319 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:40:24,410 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:40:59,472 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:41:34,531 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:42:09,623 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:42:44,701 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:43:19,775 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:43:55,172 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:44:30,245 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:45:05,361 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:45:40,431 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:46:15,507 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:46:50,580 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:47:25,667 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:48:00,732 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:48:35,802 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:49:11,023 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:49:46,091 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:50:21,161 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:50:56,263 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

2020-03-25 01:51:31,332 ERROR 4662 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

